-- ==============================================================================
-- Nexgen Employee Management System (EMS) - Supabase Database Schema & Seed Data
-- ==============================================================================
-- Instructions:
-- 1. Open your Supabase Project Dashboard -> SQL Editor.
-- 2. Paste this entire file into the SQL Editor and click "Run".
-- 3. To link your Supabase Auth admin user to the employee table, run:
--    UPDATE public.employee SET auth_user_id = '<YOUR_SUPABASE_AUTH_USER_UUID>' WHERE email = 'admin@nexgen.com';
-- ==============================================================================

BEGIN;

-- ------------------------------------------------------------------------------
-- 1. CREATE TABLES
-- ------------------------------------------------------------------------------

-- Table: public.department
CREATE TABLE IF NOT EXISTS public.department (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    location TEXT,
    manager_id BIGINT
);

-- Table: public.employee
CREATE TABLE IF NOT EXISTS public.employee (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    department_id BIGINT REFERENCES public.department(department_id) ON DELETE SET NULL,
    manager_employee_id BIGINT REFERENCES public.employee(employee_id) ON DELETE SET NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    gender TEXT CHECK (gender IN ('M', 'F')),
    email TEXT NOT NULL UNIQUE,
    hire_date DATE NOT NULL DEFAULT CURRENT_DATE,
    job_title TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'on_leave', 'terminated')),
    role TEXT NOT NULL DEFAULT 'employee' CHECK (role IN ('admin', 'manager', 'employee')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add Circular Foreign Key for department manager
ALTER TABLE public.department 
    DROP CONSTRAINT IF EXISTS fk_department_manager,
    ADD CONSTRAINT fk_department_manager 
    FOREIGN KEY (manager_id) REFERENCES public.employee(employee_id) ON DELETE SET NULL;

-- Table: public.project
CREATE TABLE IF NOT EXISTS public.project (
    project_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT REFERENCES public.department(department_id) ON DELETE SET NULL,
    manager_id BIGINT REFERENCES public.employee(employee_id) ON DELETE SET NULL,
    project_name TEXT NOT NULL,
    start_date DATE,
    end_date DATE,
    budget NUMERIC(12, 2),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'on_hold', 'cancelled'))
);

-- Table: public.assignment
CREATE TABLE IF NOT EXISTS public.assignment (
    employee_id BIGINT REFERENCES public.employee(employee_id) ON DELETE CASCADE,
    project_id BIGINT REFERENCES public.project(project_id) ON DELETE CASCADE,
    assigned_role TEXT,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (employee_id, project_id)
);

-- Table: public.attendance
CREATE TABLE IF NOT EXISTS public.attendance (
    attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES public.employee(employee_id) ON DELETE CASCADE,
    attendance_date DATE NOT NULL,
    check_in TIME,
    check_out TIME,
    status TEXT NOT NULL CHECK (status IN ('present', 'absent', 'late', 'half_day')),
    hours_worked NUMERIC(4, 2)
);

-- Table: public.leaves
CREATE TABLE IF NOT EXISTS public.leaves (
    leave_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES public.employee(employee_id) ON DELETE CASCADE,
    leave_type TEXT NOT NULL CHECK (leave_type IN ('sick', 'casual', 'annual', 'unpaid')),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason TEXT,
    approval_status TEXT NOT NULL DEFAULT 'pending' CHECK (approval_status IN ('pending', 'approved', 'rejected')),
    approved_by BIGINT REFERENCES public.employee(employee_id) ON DELETE SET NULL,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Table: public.payroll
CREATE TABLE IF NOT EXISTS public.payroll (
    payroll_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES public.employee(employee_id) ON DELETE CASCADE,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    gross_pay NUMERIC(10, 2) NOT NULL,
    net_pay NUMERIC(10, 2) NOT NULL,
    pay_date DATE,
    payment_status TEXT NOT NULL DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'failed'))
);

-- Table: public.audit_log
CREATE TABLE IF NOT EXISTS public.audit_log (
    audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_employee_id BIGINT REFERENCES public.employee(employee_id) ON DELETE SET NULL,
    entity_type TEXT NOT NULL,
    entity_id BIGINT,
    action TEXT NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    old_values JSONB,
    new_values JSONB
);

-- Table: public.user_preferences
CREATE TABLE IF NOT EXISTS public.user_preferences (
    employee_id BIGINT PRIMARY KEY REFERENCES public.employee(employee_id) ON DELETE CASCADE,
    theme_mode TEXT NOT NULL DEFAULT 'light' CHECK (theme_mode IN ('light', 'dark')),
    accent_color TEXT NOT NULL DEFAULT 'blue' CHECK (accent_color IN ('red', 'blue', 'green', 'purple', 'orange', 'yellow'))
);

-- ------------------------------------------------------------------------------
-- 2. DISABLE RLS OR ADD PERMISSIVE POLICIES FOR INITIAL SETUP
-- ------------------------------------------------------------------------------

ALTER TABLE public.department ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaves ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payroll ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;

-- Helper macro to grant full access to authenticated & anon users for local development / testing
DO $$ 
DECLARE
    tbl text;
BEGIN
    FOR tbl IN 
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
          AND table_name IN ('department', 'employee', 'project', 'assignment', 'attendance', 'leaves', 'payroll', 'audit_log', 'user_preferences')
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Allow all authenticated users access to %I" ON public.%I;', tbl, tbl);
        EXECUTE format('CREATE POLICY "Allow all authenticated users access to %I" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true);', tbl, tbl);
        
        EXECUTE format('DROP POLICY IF EXISTS "Allow anon users access to %I" ON public.%I;', tbl, tbl);
        EXECUTE format('CREATE POLICY "Allow anon users access to %I" ON public.%I FOR ALL TO anon USING (true) WITH CHECK (true);', tbl, tbl);
    END LOOP;
END $$;

-- ------------------------------------------------------------------------------
-- 3. SEED SAMPLE DATA
-- ------------------------------------------------------------------------------

-- Clean existing data (Optional: un-comment if starting clean)
-- TRUNCATE public.assignment, public.attendance, public.leaves, public.payroll, public.audit_log, public.user_preferences, public.project, public.employee, public.department RESTART IDENTITY CASCADE;

-- Insert Departments
INSERT INTO public.department (department_id, name, location) VALUES
(1, 'Engineering', 'Building A - 3rd Floor'),
(2, 'Human Resources', 'Building B - 1st Floor'),
(3, 'Marketing & Growth', 'Building A - 4th Floor'),
(4, 'Product & Design', 'Building A - 2nd Floor'),
(5, 'Finance & Operations', 'Building B - 2nd Floor')
ON CONFLICT (department_id) DO UPDATE SET 
    name = EXCLUDED.name, 
    location = EXCLUDED.location;

-- Insert Employees (Admins, Managers, Employees)
INSERT INTO public.employee 
(employee_id, first_name, last_name, gender, email, hire_date, job_title, status, role, department_id, manager_employee_id) 
VALUES
-- Admin (System Level)
(1, 'Sarah', 'Connor', 'F', 'admin@nexgen.com', '2023-01-15', 'System Administrator', 'active', 'admin', NULL, NULL),

-- Managers
(2, 'Alex', 'Rivera', 'M', 'alex.rivera@nexgen.com', '2023-03-01', 'Engineering Manager', 'active', 'manager', 1, 1),
(3, 'Emily', 'Watson', 'F', 'emily.watson@nexgen.com', '2023-04-10', 'HR Director', 'active', 'manager', 2, 1),
(4, 'David', 'Chen', 'M', 'david.chen@nexgen.com', '2023-05-20', 'Marketing Lead', 'active', 'manager', 3, 1),

-- Engineering Employees
(5, 'Michael', 'Scott', 'M', 'michael.scott@nexgen.com', '2023-06-01', 'Senior Fullstack Engineer', 'active', 'employee', 1, 2),
(6, 'Jim', 'Halpert', 'M', 'jim.halpert@nexgen.com', '2023-07-15', 'Frontend Developer', 'active', 'employee', 1, 2),
(7, 'Pam', 'Beesly', 'F', 'pam.beesly@nexgen.com', '2023-08-01', 'UI/UX Engineer', 'active', 'employee', 1, 2),

-- HR & Marketing Employees
(8, 'Dwight', 'Schrute', 'M', 'dwight.schrute@nexgen.com', '2023-09-10', 'HR Specialist', 'active', 'employee', 2, 3),
(9, 'Angela', 'Martin', 'F', 'angela.martin@nexgen.com', '2023-10-05', 'Financial Analyst', 'active', 'employee', 5, 1),
(10, 'Ryan', 'Howard', 'M', 'ryan.howard@nexgen.com', '2023-11-12', 'Growth Marketer', 'on_leave', 'employee', 3, 4)
ON CONFLICT (employee_id) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    gender = EXCLUDED.gender,
    email = EXCLUDED.email,
    hire_date = EXCLUDED.hire_date,
    job_title = EXCLUDED.job_title,
    status = EXCLUDED.status,
    role = EXCLUDED.role,
    department_id = EXCLUDED.department_id,
    manager_employee_id = EXCLUDED.manager_employee_id;

-- Update Department Managers
UPDATE public.department SET manager_id = 2 WHERE department_id = 1;
UPDATE public.department SET manager_id = 3 WHERE department_id = 2;
UPDATE public.department SET manager_id = 4 WHERE department_id = 3;

-- Insert Projects
INSERT INTO public.project 
(project_id, department_id, manager_id, project_name, start_date, end_date, budget, status) 
VALUES
(1, 1, 2, 'Nexgen EMS Portal Redesign', '2026-01-10', '2026-09-30', 75000.00, 'active'),
(2, 1, 2, 'Cloud Infrastructure Migration', '2026-03-01', '2026-11-15', 120000.00, 'active'),
(3, 3, 4, 'Q3 Global Brand Campaign', '2026-05-01', '2026-08-31', 45000.00, 'active'),
(4, 2, 3, 'Automated Employee Onboarding', '2025-10-01', '2026-04-30', 30000.00, 'completed')
ON CONFLICT (project_id) DO UPDATE SET
    department_id = EXCLUDED.department_id,
    manager_id = EXCLUDED.manager_id,
    project_name = EXCLUDED.project_name,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    budget = EXCLUDED.budget,
    status = EXCLUDED.status;

-- Insert Project Assignments
INSERT INTO public.assignment (employee_id, project_id, assigned_role, assigned_at) VALUES
(5, 1, 'Lead Backend Engineer', NOW() - INTERVAL '60 days'),
(6, 1, 'Frontend Lead', NOW() - INTERVAL '60 days'),
(7, 1, 'UI/UX Designer', NOW() - INTERVAL '50 days'),
(5, 2, 'DevOps Consultant', NOW() - INTERVAL '30 days'),
(10, 3, 'Campaign Manager', NOW() - INTERVAL '40 days'),
(8, 4, 'HR Coordinator', NOW() - INTERVAL '100 days')
ON CONFLICT (employee_id, project_id) DO UPDATE SET
    assigned_role = EXCLUDED.assigned_role;

-- Insert Attendance Records
INSERT INTO public.attendance 
(attendance_id, employee_id, attendance_date, check_in, check_out, status, hours_worked) 
VALUES
-- Recent attendance for Michael Scott (Emp 5)
(1, 5, CURRENT_DATE - INTERVAL '3 days', '09:00:00', '17:30:00', 'present', 8.5),
(2, 5, CURRENT_DATE - INTERVAL '2 days', '09:15:00', '17:45:00', 'late', 8.5),
(3, 5, CURRENT_DATE - INTERVAL '1 day',  '08:55:00', '17:00:00', 'present', 8.08),
(4, 5, CURRENT_DATE,                   '09:02:00', NULL,       'present', NULL),

-- Attendance for Jim Halpert (Emp 6)
(5, 6, CURRENT_DATE - INTERVAL '3 days', '08:58:00', '17:00:00', 'present', 8.03),
(6, 6, CURRENT_DATE - INTERVAL '2 days', '09:00:00', '17:15:00', 'present', 8.25),
(7, 6, CURRENT_DATE - INTERVAL '1 day',  '09:30:00', '17:30:00', 'late', 8.0),
(8, 6, CURRENT_DATE,                   '08:50:00', NULL,       'present', NULL),

-- Attendance for Pam Beesly (Emp 7)
(9, 7, CURRENT_DATE - INTERVAL '3 days', '09:05:00', '17:00:00', 'present', 7.91),
(10, 7, CURRENT_DATE - INTERVAL '2 days', '09:00:00', '13:00:00', 'half_day', 4.0),
(11, 7, CURRENT_DATE - INTERVAL '1 day',  '08:50:00', '17:10:00', 'present', 8.33),
(12, 7, CURRENT_DATE,                  '09:00:00', NULL,       'present', NULL),

-- Attendance for Ryan Howard (Emp 10 - On Leave)
(13, 10, CURRENT_DATE - INTERVAL '1 day', NULL, NULL, 'absent', 0.0)
ON CONFLICT (attendance_id) DO NOTHING;

-- Insert Leave Requests
INSERT INTO public.leaves 
(leave_id, employee_id, leave_type, start_date, end_date, reason, approval_status, approved_by, requested_at) 
VALUES
(1, 10, 'annual', CURRENT_DATE - INTERVAL '2 days', CURRENT_DATE + INTERVAL '5 days', 'Summer vacation trip with family.', 'approved', 4, NOW() - INTERVAL '10 days'),
(2, 6,  'sick',   CURRENT_DATE + INTERVAL '3 days', CURRENT_DATE + INTERVAL '4 days', 'Scheduled medical checkup.', 'pending', NULL, NOW() - INTERVAL '1 day'),
(3, 7,  'casual', CURRENT_DATE - INTERVAL '15 days', CURRENT_DATE - INTERVAL '14 days', 'Personal errands.', 'approved', 2, NOW() - INTERVAL '20 days'),
(4, 5,  'unpaid', CURRENT_DATE - INTERVAL '40 days', CURRENT_DATE - INTERVAL '38 days', 'Attending tech conference overseas.', 'rejected', 2, NOW() - INTERVAL '45 days')
ON CONFLICT (leave_id) DO NOTHING;

-- Insert Payroll Records
INSERT INTO public.payroll 
(payroll_id, employee_id, period_start, period_end, gross_pay, net_pay, pay_date, payment_status) 
VALUES
(1, 1, '2026-07-01', '2026-07-31', 12000.00, 9500.00, '2026-07-31', 'paid'),
(2, 2, '2026-07-01', '2026-07-31', 9500.00,  7600.00, '2026-07-31', 'paid'),
(3, 3, '2026-07-01', '2026-07-31', 8800.00,  7040.00, '2026-07-31', 'paid'),
(4, 4, '2026-07-01', '2026-07-31', 8200.00,  6560.00, '2026-07-31', 'paid'),
(5, 5, '2026-07-01', '2026-07-31', 7500.00,  6000.00, '2026-07-31', 'paid'),
(6, 6, '2026-07-01', '2026-07-31', 6200.00,  4960.00, '2026-07-31', 'paid'),
(7, 7, '2026-07-01', '2026-07-31', 5800.00,  4640.00, '2026-07-31', 'paid'),
(8, 8, '2026-07-01', '2026-07-31', 5500.00,  4400.00, '2026-07-31', 'paid'),
(9, 9, '2026-07-01', '2026-07-31', 6000.00,  4800.00, '2026-07-31', 'paid'),
(10, 10, '2026-07-01', '2026-07-31', 5200.00, 4160.00, '2026-07-31', 'paid'),

-- Upcoming pending payroll batch for August
(11, 5, '2026-08-01', '2026-08-31', 7500.00,  6000.00, NULL, 'pending'),
(12, 6, '2026-08-01', '2026-08-31', 6200.00,  4960.00, NULL, 'pending'),
(13, 7, '2026-08-01', '2026-08-31', 5800.00,  4640.00, NULL, 'pending')
ON CONFLICT (payroll_id) DO NOTHING;

-- Insert User Preferences
INSERT INTO public.user_preferences (employee_id, theme_mode, accent_color) VALUES
(1, 'dark',  'purple'),
(2, 'dark',  'blue'),
(3, 'light', 'green'),
(4, 'light', 'orange'),
(5, 'dark',  'blue'),
(6, 'light', 'blue'),
(7, 'dark',  'purple'),
(8, 'light', 'yellow'),
(9, 'light', 'green'),
(10, 'dark', 'red')
ON CONFLICT (employee_id) DO UPDATE SET
    theme_mode = EXCLUDED.theme_mode,
    accent_color = EXCLUDED.accent_color;

-- Insert Sample Audit Log
INSERT INTO public.audit_log 
(audit_log_id, actor_employee_id, entity_type, entity_id, action, changed_at, old_values, new_values) 
VALUES
(1, 1, 'employee', 5, 'CREATE', NOW() - INTERVAL '30 days', NULL, '{"first_name": "Michael", "last_name": "Scott", "role": "employee"}'),
(2, 2, 'project', 1, 'UPDATE', NOW() - INTERVAL '15 days', '{"budget": 60000}', '{"budget": 75000}'),
(3, 4, 'leaves', 1, 'APPROVE', NOW() - INTERVAL '10 days', '{"status": "pending"}', '{"status": "approved"}')
ON CONFLICT (audit_log_id) DO NOTHING;

-- ------------------------------------------------------------------------------
-- 4. RESTART SEQUENCE SEEDS
-- ------------------------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('public.department', 'department_id'), COALESCE((SELECT MAX(department_id) FROM public.department), 1));
SELECT setval(pg_get_serial_sequence('public.employee', 'employee_id'), COALESCE((SELECT MAX(employee_id) FROM public.employee), 1));
SELECT setval(pg_get_serial_sequence('public.project', 'project_id'), COALESCE((SELECT MAX(project_id) FROM public.project), 1));
SELECT setval(pg_get_serial_sequence('public.attendance', 'attendance_id'), COALESCE((SELECT MAX(attendance_id) FROM public.attendance), 1));
SELECT setval(pg_get_serial_sequence('public.leaves', 'leave_id'), COALESCE((SELECT MAX(leave_id) FROM public.leaves), 1));
SELECT setval(pg_get_serial_sequence('public.payroll', 'payroll_id'), COALESCE((SELECT MAX(payroll_id) FROM public.payroll), 1));
SELECT setval(pg_get_serial_sequence('public.audit_log', 'audit_log_id'), COALESCE((SELECT MAX(audit_log_id) FROM public.audit_log), 1));

COMMIT;
